name: mindpause
description: Εφαρμογή μικροπαρεμβάσεων για μείωση άγχους

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  fl_chart: ^1.2.0
  google_fonts: ^8.1.0
  intl: ^0.20.2
  flutter_tts: ^3.6.7
  just_audio: ^0.10.5
  audio_session: ^0.1.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  sqflite_common: ^2.5.6
  sqflite_common_ffi: ^2.3.6
  flutter_local_notifications: ^17.1.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - MindPause_backround_music.mp3
